# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruity', '0003_auto_20160606_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_round',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
