# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruity', '0004_player_last_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_round',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
