# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruity', '0005_auto_20160606_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_playing',
            field=models.BooleanField(default=False),
        ),
    ]
